import type { Metadata } from "next";
import Navigation from "./_components/Navigation";
import "./globals.css";
import { merriweather, montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`text-body bg-background mx-auto pb-20 antialiased ${merriweather.variable} ${montserrat.variable}`}
      >
        <header className="bg-hero-bg px-10 pt-8">
          <div className="mx-auto flex max-w-5xl flex-col items-center justify-center">
            <Navigation className="w-full" />
          </div>
        </header>
        <div>{children}</div>
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
