import type { Metadata } from "next";
import Navigation from "./_components/Navigation";
import "./globals.css";
import { ibm } from "./fonts";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased max-w-4xl mx-auto py-14 px-4 ${ibm.className}`}
      >
        <header>
          <Navigation />
        </header>
        <div className="mt-4">{children}</div>
      </body>
    </html>
  );
}
