name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: alantayyx/next-pi-app
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
  deploy:
    name: Rollout Restart on Pi
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Restart Kubernetes Deployment
        run: |
          kubectl rollout restart deployment next-pi-app

